site_name: Alves | Base de Conhecimento Técnico
site_description: Portal de estudos focado em Auto Cad, automação CAD usando Auto Lisp e Python, Topografia e Projetos.
site_author: Jefter Alves

theme:
  name: material
  features:
    - navigation.tabs # Cria um menu superior elegante
    - search.suggest # Deixa a barra de busca mais inteligente
  palette:
    scheme: slate # Ativa um modo escuro (Dark Mode) nativo e moderno
    primary: indigo

  nav:
  - Início: index.md
  - 📋 Normas e Procedimentos:
  - ⚙️ Fluxos e Processos:
  - 📚 Base Teórica:

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg