site_name: Manuais e Documentação Técnica
site_description: Portal de estudos focado em topografia, geodésia e automação CAD.
site_author: Jefter

theme:
  name: material
  features:
    - navigation.tabs # Cria um menu superior elegante
    - search.suggest # Deixa a barra de busca mais inteligente
  palette:
    scheme: slate # Ativa um modo escuro (Dark Mode) nativo e moderno
    primary: indigo

  nav:
  - Início: index.md
  - Automação CAD:
    - Rotinas em AutoLISP: automacao/Lisp.md
  - Topografia e Geodésia:
  - Engenharia e Infraestrutura:

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg